name: test decoder and encoder flow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the vta-bert branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '04 8 * * *'
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        mode-name:
          type: choice
          description: build version
          options: 
          - aie_noop
          - aie_build
          - aie_load
          - cpu
        model-name:
          type: choice
          description: model
          options: 
          - decoder
          - encoder
          - both

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"  
  
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Run git submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - name: lint check 
        run: |   
         echo '-------lint-------'

  test-decoder-encoder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Run git submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - name: clone MellowCoco
        uses: actions/checkout@v3
        with:
          repository: ssuxue/MellowCoco
          path: utils/
          ref: main
      - name: Build docker image
        run: |
          ll -l
          ll -l utils
          echo "build docker images"
      - name: build tvm
        run: |
          echo "build tvm"
      - name: test encoder and decoder
        run: |
          ll -l
          ll -l utils
          echo "test encoder and decoder"
  test-input:
      runs-on: ubuntu-latest
      steps:
      - name: Print outputs
        run: |
          echo ${{ github.event_name }} 
          echo "${{ github.event.inputs.mode-name }} - ${{ github.event.inputs.model-name }}"
