name: Test Rerun


on:
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test1:
    runs-on: ubuntu-latest
    name: Test Case1
    steps:
      - uses: actions/checkout@v3

      - name: Case1
        run: |
          echo "test case1"

  test2:
    runs-on: ubuntu-latest
    name: Test Case2
    steps:
      - uses: actions/checkout@v3

      - name: Case2
        run: |
          echo "test case2

  auto-rerun:
    runs-on: ubuntu-latest
    needs: test2
    if: always()
    env:
      MAX_RETRIES: 2

    steps:
      - name: Check Workflow Conclusion
        continue-on-error: true
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "failure" ]; then
          retries=$(expr ${{ github.event.workflow_run.re-run }} + 1)

          if [ "$retries" -le $MAX_RETRIES ]; then
            echo "Retrying, attempt $retries..."
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/test-rerun.yml/dispatches" \
              -d '{"ref": "${{ github.event.workflow_run.head_commit.id }}"}'
          else
            echo "Max retries reached, no more reruns triggered."
          fi
        else
          echo "Workflow succeeded, no rerun triggered."
        fi
